### ISSUE TITLE
Way to create custom content in day cell?

### ISSUE THREAD

**Issue by wonder95** [EazyServer/Vue-Bootstrap-Calendar#11]
I have an app that I wrote in Angularjs that uses an [Angular version of bootstrap-calendar](https://github.com/mattlewis92/angular-bootstrap-calendar) that I would like to convert to use Vue.js. What I was doing was using the calendar only for the structure, and [using a custom template to place my own custom content within the cell](https://github.com/mattlewis92/angular-bootstrap-calendar/issues?q=is%3Aissue+author%3Awonder95+is%3Aclosed). Is that something that is possible with this implementation? I'm just getting up to speed on Vue, so apologies if this is fairly obvious.

Thanks.

**Comment by EazyServer** [comment]
Hi @wonder95 

If you want custom implementation/design then you need to include source code directly into your code, [Calendar.vue](https://github.com/EazyServer/Vue-Bootstrap-Calendar/blob/master/src/Calendar.vue) is a good starting point.
Just make sure to provide all dependencies (i.e. `moment`, `CHANGE_MONTH`, `CalendarHeader`, `Week`) and dependencies of sub-dependencies if there are any and so on.. That should be it

**Comment by wonder95** [comment]
I don't understand. For instance, there's no way to somehow override 'Day.vue'? Or do I have to include everything from your component in mine and then add my own code for the day content?
