### ISSUE TITLE
Failed to mount component: template or render function not defined. 

### ISSUE THREAD

**Issue by ddydeveloper** [EazyServer/Vue-Bootstrap-Calendar#12]
I use component in this way: 

```
<template>
    <calendar :first-day="1" :all-events="[]"></calendar>
</template>

<script>
    import { Calendar } from 'vue-bootstrap-calendar';
    export default {
            components: { VueInfoPanel, Calendar }
        }
    }
</script>    
```

As result I get this error: Failed to mount component: template or render function not defined. 
Is it related with ingoring of the locale configuration (vue-i18n)? 

npm version: ""^2.5.9""
vue version: "^2.5.9"
vue-bootstrap-calendar version: "^1.3.3"

**Comment by wonder95** [comment]
See answer to [my same issue here](https://github.com/EazyServer/Vue-Bootstrap-Calendar/issues/13#issuecomment-349592334).

**Comment by ddydeveloper** [comment]
@wonder95 Thanks! A had the same issue even if I use i18n in accordance with documentation

**Comment by EazyServer** [comment]
Sorry @ddydeveloper I just saw that you reported this issue a while ago!

I think there is a problem in exporting `Calendar` module! At the moment it's been exported as a generic object instead of a Vue component!

![screen shot 2017-12-08 at 23 35 45](https://user-images.githubusercontent.com/19202935/33789552-359e3254-dc71-11e7-9b0f-e8c23ee4a515.png)

This is my export in `main.js`

![screen shot 2017-12-08 at 23 40 59](https://user-images.githubusercontent.com/19202935/33789568-59bf86a6-dc71-11e7-91eb-aa6bc7220fd8.png)

Looks like my webpack configs fails to export as VueComponent!

**Comment by EazyServer** [comment]
I added a fix, please install 1.3.4 and let me know. thanks

**Comment by wonder95** [comment]
It's better in that I'm getting the calendar header now, but I still get the same error (see screenshot).

![vcb_error_134](https://user-images.githubusercontent.com/201936/34220776-aa681e7c-e56a-11e7-8e4e-b25ae2d4495e.png)

**Comment by onekiloparsec** [comment]
Same problem here. I'm glad you seem to be "on it".

I'm not fluent with webpack. I find it very hard to master... I've recently used "rollup.js" to publish a component (`@onekiloparsec/vue-xeditable`). But this is an completely new setup.

**Comment by wonder95** [comment]
Yes, I'm hoping @EazyServer hasn't forgotten about this. :-P

**Comment by EazyServer** [comment]
@wonder95 I was on holiday, I will be looking at this soon.

**Comment by EazyServer** [comment]
please install 1.3.5 and let me know. thanks

**Comment by EazyServer** [comment]
please install 1.3.6 and let me know. thanks

**Comment by wonder95** [comment]
Looks awesome!

Thanks.
![vue-bootstrap-slandar-working](https://user-images.githubusercontent.com/201936/34855540-1b12802c-f6f5-11e7-81db-1bf97aa2beb3.png)

**Comment by claudeberube** [comment]
Ok I see. But, this code was not merged in the bootstrap 4 version yet.
Your version is working fine.  Altought, the models are not present such as the Bootstrap 4 version.

Was able to make Boootrap 4 version run with your fixed, but with many issues:
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
vue.esm.js?efeb:578 [Vue warn]: Duplicate keys detected: '[object Object],
