### ISSUE TITLE
How Use My own Structure for Event 

### ISSUE THREAD

**Issue by ranjith2546** [EazyServer/Vue-Bootstrap-Calendar#14]
{ 
title: ''
value: {
dt: new Date()
}
}

How to use this structure in event calendar i tried but date is not working

**Comment by EazyServer** [comment]
events array must be in this format:

![image](https://user-images.githubusercontent.com/19202935/34982978-ef9dca0c-faa3-11e7-8251-6b51e4f29de0.png)
