### ISSUE TITLE
Package.json main missing?

### ISSUE THREAD

**Issue by mejcz** [EazyServer/Vue-Bootstrap-Calendar#2]
Hi!

I wanted to install your package via npm and use it with webpack. Unfortunately when I've imported Calendar weback was not able to resolve 'vue-bootstrap-calendar'. I've added `main` property to package.json pointing to `dist/vue-package.js` (next even to `Calendar.vue` itself) but even then I couldn't use your component due `Failed to mount component: template or render function not defined` error. 

I've noticed that your demo is not relaying on npm package (on dist file), is your package ready to use?

**Comment by EazyServer** [comment]
Hello,

Thanks for reporting this. I am using local referencing on my demo implementation and that's why I never got this error!

I have now, however,  updated the package to reference to the correct file and added more details on how to use the package correctly.
