### ISSUE TITLE
31st of July possible bug?

### ISSUE THREAD

**Issue by LicaSterian** [EazyServer/Vue-Bootstrap-Calendar#8]
From the below attatchment today, 31st of july isn't visible on the current month view.

![31st-of-july-bug](https://user-images.githubusercontent.com/8027455/28779811-1edc67c2-760d-11e7-91ec-835282678e25.jpg)

Is this a known issue? Is it by design, so that we only see 5 weeks per month?
Thanks.

**Comment by EazyServer** [comment]
Thanks for point it out. will have a look at

**Comment by EazyServer** [comment]
Issue is now rectified. Thanks
