### ISSUE TITLE
Error on install in Laravel

### ISSUE THREAD

**Issue by vesteves** [EazyServer/Vue-Bootstrap-Calendar#9]
``` ERROR  Failed to compile with 1 errors                                 15:36:34

 error  in ./~/vue-bootstrap-calendar/src/Calendar.vue

Module build failed: Error: Couldn't find preset "latest" relative to directory "[PROJECT]/node_modules/vue-bootstrap-calendar"
    at [PROJECT]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
```

Any idea wt should I do?

**Comment by EazyServer** [comment]
Looks like an issue with your setup rather than the package! 
can you please provide more details on the setup? i.e. is it gulp, webpack, etc

**Comment by EazyServer** [comment]
I run into the same issue! and the solution was to install [babel-preset-latest](https://www.npmjs.com/package/babel-preset-latest).

Better late than never!

Thanks

**Comment by vesteves** [comment]
Oh! It's nice. Maybe now I can back to this repo =)
